# frozen_string_literal: true

require "pathname"

module CustomId
  # Manages the Rails initializer file that auto-includes {CustomId::Concern}
  # into every ActiveRecord model via +ActiveSupport.on_load(:active_record)+.
  #
  # This class is intentionally decoupled from Rails so it can be exercised in
  # unit tests without booting a full Rails application.
  class Installer
    # Path of the generated initializer, relative to the Rails root.
    INITIALIZER_PATH = Pathname.new("config/initializers/custom_id.rb")

    # Content written to the initializer file.
    INITIALIZER_CONTENT = <<~RUBY
      # frozen_string_literal: true

      # Auto-include CustomId::Concern into every ActiveRecord model so that
      # the +cid+ class macro is available application-wide.
      #
      # Generated by: rails custom_id:install
      ActiveSupport.on_load(:active_record) do
        include CustomId::Concern
      end
    RUBY

    # Creates the initializer file under +rails_root+.
    #
    # @param rails_root [Pathname, String] Root of the Rails application.
    # @return [:created] when the file was written.
    # @return [:skipped] when the file already exists.
    def self.install!(rails_root)
      target = Pathname(rails_root).join(INITIALIZER_PATH)
      return :skipped if target.exist?

      target.dirname.mkpath
      target.write(INITIALIZER_CONTENT)
      :created
    end

    # Removes the initializer file from +rails_root+.
    #
    # @param rails_root [Pathname, String] Root of the Rails application.
    # @return [:removed] when the file was deleted.
    # @return [:skipped] when the file did not exist.
    def self.uninstall!(rails_root)
      target = Pathname(rails_root).join(INITIALIZER_PATH)
      return :skipped unless target.exist?

      target.delete
      :removed
    end
  end
end
